apiVersion: v1	
kind: Service	
metadata:	
  name: guestbook-ui
  annotations:
    external-dns.alpha.kubernetes.io/hostname: <+stage.name>.magic.lab.local
spec:	
  ports:	
  - port: 80	
    targetPort: 80	
  selector:	
    app: guestbook-ui
