apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-lb
  annotations:
    external-dns.alpha.kubernetes.io/hostname: <+stage.name>.magic.lab.local
spec:
  selector:
    app: guestbook-ui
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80