apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-lb-primary
  annotations:  
    harness.io/primary-service: "true"
spec:
  selector:
    app: guestbook-ui
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-lb-stage
  annotations:  
    harness.io/stage-service: "true"
spec:
  selector:
    app: guestbook-ui
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80