service:
  name: harnessguestbook
  identifier: harnessguestbook
  serviceDefinition:
    type: Kubernetes
    spec:
      manifests:
        - manifest:
            identifier: guestbook
            type: Kustomize
            spec:
              store:
                type: Github
                spec:
                  connectorRef: rbutler
                  gitFetchType: Branch
                  folderPath: kustomize-guestbook
                  branch: master
              pluginPath: ""
              skipResourceVersioning: false
              enableDeclarativeRollback: false
  gitOpsEnabled: false